### ISSUE TITLE
Structure docs around four quadrants

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#1023]
I recently read https://www.divio.com/blog/documentation/, check it out if you haven't yet.

This article makes a convincing case for structuring documentation across four functions:
- Tutorials
- How-to guides
- Explanation
- Reference

Lighthouse currently offers a very basic tutorial and kind of mixes the remaining three categories. While the docs are quite good already, we can still improve the structure and depth.

We could start out by splitting the docs into the four quadrants, then building them up to be more complete.

What do you think?

**Comment by HendrikJan** [comment]
I like the idea.  

A how-to section would be my first place to look when I encounter new challenges.  
In my experience many of my problems are easily solved when you know how to, but are difficult to find an answer for in the current documentation.  
Examples of questions that I had/have that could be answered in a how-to guide:
- How can I access the values in a pivot-table?
- How can I put values in a pivot-table?
- How can I validate a field based on the value in a related table?
- How can I filter the results of a query on the values in a related table?
- How can I filter the results of a query on the values in a deeply nested table?
- How can I use websockets with Laravel Lighthouse?

A good written explanation section could be useful as well.  
That would be something that I'd read "for fun" when I had no specific goal.  
Examples of topics that I would have fun reading:
- The order of execution in Lighthouse and Laravel
- Why were some design choices made in Lighthouse

The "API reference" in the current documentation seems like a good start for the "Reference" quadrant.

I didn't read the whole article, but what I read sounds very sensible.

**Comment by Jofairden** [comment]
I agree mostly with the above comment.
I think How-Tos are meant to be clear-cut "how to do X or Y thing", simply showing a concrete example in code of how to work with the specified usecase. E.g. "How do I make a @hasMany relation return paginated results?" You get the idea.

I think tutorials don't need to be explained here, they go in-depth into certain subjects (such as config), telling you what to do and briefly explaining why. Explanation articles can be used to explain complex matters such as what GraphQL actually is and the resulting Schema being a Graph and how to traverse one efficiently.

For example I think currently the docs contain lots of information, but not only is there still information missing (I still don't really know what @inject does, is it because I don't use mutations?) but there also really isn't a clear path you follow. You just move along and once you've done the configuration, it's kind of like "just go and figure it out by trial and error, you'll come back if you have an issue".

**Comment by spawnia** [comment]
Closing this but will keep it in mind.
