### ISSUE TITLE
Method to purge results cached with "@cache" directive.

### ISSUE THREAD

**Issue by GregPeden** [nuwave/lighthouse#1049]
The @cache directive includes the option to command a result to be cached without limit, but there is not a built-in method to clear or reset cached results. This can cause deployment issues or issues related to affecting design changes during debugging.

A built-in method to clear all cached query results, or a specific named query route cache.

Clearing the cache can also be affected through system reboot or other similar substantial actions.

**Comment by spawnia** [comment]
@SirLamer open for PR's. Is there a way to organize the cache entries so they can be cleared reliably?

**Comment by SirLamer** [comment]
Sorry I missed your reply until recently.

I am not especially familiar with Lighthouse behind the scenes or how various caching techniques work, however in general I think that if cache keys all start with a unique tag like "nuwave-lighthouse-cache" or whatever then I think they can be searched and cleared.

**Comment by spawnia** [comment]
Laravel seems to have a method to clear single cache entries, see https://laravel.com/docs/cache#removing-items-from-the-cache

**Comment by dinhkhanh** [comment]
@spawnia you absolutely use Laravel built-in functions to delete the caches. The thing is, how to determine the cache key of given query? Lighthouse should provides a function to get cache key of any query. 

I see function `getKey` in `CacheValue` class but the class itself requires too many construct parameters that not too easy to get from anywhere.

**Comment by spawnia** [comment]
@dinhkhanh The `CacheValue` is not meant for usage outside of the context of resolving a query. I suppose we could extract a utility function to determine a cache key, but it requires a lot of arguments in order to be unique.

Caching is not done per query but rather on the level of individual fields. Lighthouse also takes the arguments into account that are passed into the field. There can also be private caches that are uniquely tied to a specific user.

**Comment by dinhkhanh** [comment]
I see your point.

I have an example.

```graphql
type Profile {
  username: String @cacheKey
  repos: [Repository] @cache
}
```

```graphql
type Query {
  getProfile(username: String!) : Profile
}
```

Once a repo is updated/added to `Repository`, so far, is there any suggestion on cache invalidation of above query?

**Comment by wimil** [comment]
I have the same problem, I am saving the user's shorteners relation, but when adding more data to the relation there is no way to clear the cache

```graphql
type User{
    id: ID!
    email: String!
    username: String!
    firstname: String
    lastname: String
    gender: String
    status: String!
    token: String!
    created_at: DateTime!
    updated_at: DateTime!
    shorteners: [Shortener!]! @belongsToMany @cache
}
```

**Comment by gferreri** [comment]
This is a big issue. In our case, we had a query with an unqualified `@cache` directive. Later, we decided that we want to invalidate every 5 minutes with `@cache(maxAge: 300)` but this has no effect on deployment. The previously cached values remain unless the entire laravel cache is cleared, which is a non-starter in production because all users will be logged out. The only recourse is to remove the `@cache` directive altogether.

**Comment by spawnia** [comment]
This is implemented by `@clearCache` - see https://lighthouse-php.com/master/performance/caching.html#clear-cache
