### ISSUE TITLE
Simplify `@whereConstraints` usage by defining it upon fields

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#1121]
The `@whereConstraints` directive is currently implemented as an argument directive.

```graphql
type Query {
    people(
        where: WhereConstraints @whereConstraints(columns: ["age", "type", "haircolour", "height"])
    ): [Person!]! @all
}
```

This schema definition carries a bit of redundancy and is even a bit misleading. It could be simpler to just define it on the field level. The argument would then be added automatically, with the name defaulting to `where` but able to be overwritten:

```graphql
type Query {
    people: [Person!]! @whereConstraints(columns: ["age", "type", "haircolour", "height"], argument: "filter") @all
}
```

That would remove some options which now exist, but are probably not used much anyways:
- Adding multiple different `@whereConstraints` args on a single field
- Adding a custom description to the generated arg

**Comment by chescos** [comment]
Is there any reason to define multiple `@whereConstraints` args on a single field? I can't think of one.

Besides that, would you consider to add a `@whereHasConstraints` directive to Lighthouse? I've posted some [code examples here](https://github.com/nuwave/lighthouse/issues/1112), maybe you can take a quick look and let me know what you think.

If we might get a `@whereHasConstraints` directive in the future, I'd say that one reason to keep `@whereConstraints` as an argument directive is to maintain things consistent (since `@whereHasConstraints` would probably require one argument per relationship).

**Comment by spawnia** [comment]
Not planning to add this for the reasons that @chescos pointed out.

Also, the current suggested syntax allows to omit the argument type:

```graphql
type Query {
  foo(bar: _ @whereConstraints)
}
```

I think that is reasonably simple.
