### ISSUE TITLE
Combining @search directive with Query Constraints

### ISSUE THREAD

**Issue by palypster** [nuwave/lighthouse#1161]
**Describe the bug**

Imagine this query definition:
```
extend type Query {
    projects(
        client: ID @eq(key: "client_id")
        search: String @search
    ): [Project!]! @paginate(defaultCount: 10)
    ...
```

I am unable to use both features at the same time:

1. filtering by `client`
1. searching

**Expected behavior/Solution**

If I run a query:
```
{
  projects (
    client: 1,
    search: "Foo Bar"
    ...
```
I get the projects matching the name `Foo Bar`  **and** from the client with id = `1`.

Instead, the Lighthouse is returning projects matching the name `Foo Bar` from **all** clients (ignoring the `client` filter).

**Environment**

Lighthouse Version: 4.8
Laravel Version: 6.2

**Comment by spawnia** [comment]
`@search` uses the `\Laravel\Scout\Builder` under the hood, which does not support all the operations that an SQL-based query builder would have, see https://laravel.com/docs/5.8/scout#where-clauses The existing query filters such as `@eq` would not work with that. 

Allowing those simple where conditions to be added to search seems reasonable, but we might need to separate this part out from other filters, since they cannot be freely combined.

I think a simple way would be to have different fields, e.g. `projects` and `projectsSearch`. That would ensure that a query wither has complex filters OR search and only basic where filters.

**Comment by palypster** [comment]
Okay, but then documentation is wrong, look:
https://lighthouse-php.com/4.8/api-reference/directives.html#search
```Regular filters such as @eq or @in still work...```

**Comment by spawnia** [comment]
@palypster i totally agree, we should change the docs. Can you add a PR?

**Comment by spawnia** [comment]
I updated the docs.
