### ISSUE TITLE
Generate all Schema by Models

### ISSUE THREAD

**Issue by menegain** [nuwave/lighthouse#1180]
Create artisan command `lighthouse:generate-schema` to generate all schema by fillable and relationships model. Example : 
Model Ticket 
```php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    protected $guard_name = 'api';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'description'
    ];

    /**
     * Get the ticket status.
     */
    public function status()
    {
        return $this->belongsTo('App\Models\TicketStatus');
    }

    /**
     * Get the ticket type.
     */
    public function type()
    {
        return $this->belongsTo('App\Models\TicketType');
    }

    /**
     * Get the message for the ticket.
     */
    public function messages()
    {
        return $this->hasMany('App\Models\Message');
    }
}
```
Generate `routes/graphql/ticket.graphql`  : 
```grapql
type Ticket {
    id: ID!
    title: String!
    description: String!
    status: TicketStatus @belongsTo
    type: TicketType @belongsTo
    messages: [Message!]! @hasMany
    created_at: DateTime!
    updated_at: DateTime!
}

extend type Query {
    ticketsAll: [Ticket!]! @all
    tickets(orderBy: [OrderByClause!] @orderBy): [Ticket!]! @paginate 
    ticket(id: ID @eq): Ticket @find
}

extend type Mutation {
    deleteTicket(id: [ID!]!): [Ticket!]! @delete
    createTicket(input: TicketInput! @spread): Ticket @create
    updateTicket(id: ID!, input: TicketInput! @spread): Ticket @update
}
...
```
We had `#import ticket.graphql` to main schema.graphql and we can generate too the status, type and message schema with the same method. What do you think ? 😄 👍

**Comment by spawnia** [comment]
This has been tried before, and i identified a few reasons why i don't want it in Lighthouse.

1. It is hard to generalize, since use cases and conventions will differ. I don't want to add a solution that only works for a few people. Adding configuration options to fit all use cases would quickly get out of hand.

2. API's should be stable and changes should be deliberate. Generating code that is internal to a project is less of an issue, but changing the code generation might break clients in a big way.

3. It does not have to be a part of Lighthouse Core. Nothing about generating a bunch of text from your models requires reaching into the internals of Lighthouse. This can easily be implemented as a plugin or a separate project.

Thanks for your interest anyways. If you build something like this, i am certainly interested and will gladly take a look. I am open to reconsidering if it is really awesome, but given the reasons i outlined i do not plan to add such a feature to Lighthouse.

**Comment by DM-la** [comment]
Hi there @menegain @spawnia I have created the package for generating schemas, you can find it here: https://github.com/DM-la/lighthouse-schema-generator . Hope it will be useful for you!
