### ISSUE TITLE
Guard directive from laravel middleware

### ISSUE THREAD

**Issue by mlazuardy-dyned** [nuwave/lighthouse#1259]
since the @middleware directive is deprecated, and i should use @guard directive in the feature. how to add middleware from laravel using guard directive or is it possible ?

for example i have Admin Middleware that in laravel route i just simply need to add `middleware('admin')`

but how to deal with the guard directive from laravel custom middleware ? thanks and sorry bad english

**Comment by spawnia** [comment]
Laravel middleware are meant to wrap around entire HTTP requests, whereas Lighthouse directives sit on a field level. Because of that semantic mismatch, the `@middleware` directive was removed. You can no longer use HTTP middleware directly through a directive.

You can use purpose built field middleware directives such as `@guard` or `@can` instead. If you need custom functionality, look into creating a custom field middleware directive.

**Comment by mlazuardy-dyned** [comment]
so @spawnia can i use extend query with multiple query like this
```
extend type Query @guard(with: ["api"]) @can(ability:'do-anything']) {

}
```
??

**Comment by spawnia** [comment]
This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)
