### ISSUE TITLE
Help with @globalId and default node query [relay]

### ISSUE THREAD

**Issue by 4levels** [nuwave/lighthouse#126]
Hi all,

I've been quite struggling with retrieving records based on their globalId.  If I'm not mistaken, I should be able to use the (automtically added) `node` query to retrieve a model by it's globalId, correct?
However, I keep getting the following error: 
```"[Image] is not a registered node and cannot be resolved.",```

This is my (abbreviated) schema:
```graphql
type Image {
  id: ID! @globalId
  filename: String
  thumbnail: String
  rating: Int
  created_at: DateTime
}
type Query {
  images: [Image!]! @paginate(type: "relay", model: "App\\Models\\Image")
}
```

The node query is constructed as follows (the id exists as it is returned by the images query):
```graphql
query getImage {
  node (id: "SW1hZ2U6MTE3MQ==") {
    _id
  } 
}
```

I'm pbbly overlooking something obvious here..

When I add a query with the `@filter` directive, I can query for the record, but only by using the database id, like so
```graphql
type Query {
  ...
  image(id: ID! @eq): Image @find(model: "App\\Models\\Image")
}
```
with query:
```graphql
query getImage {
  image (id: 1171) {
    id
    filename
    rating
  }
}
```

Things I've tried so far:
- adding the trait `HandlesGlobalId` to my Image model
- looking for a class to extend instead of the Eloquent Model class
- looking for a class to implement
- changing the configuration option `global_id_field` to `id` instead of the default `_id` (not even sure what this actually does)
- adding the `@globalId` to the image query like so: `image(id: ID! @globalId @eq): Image @find(model: "App\\Models\\Image")`

*sigh* the lack of documentation has been proven very time consuming, I've been reading through classes, PR's, tests, example projects, comments, etc etc but all to no avail.  Starting at lightspeed but having snail progress with the last 5% is very frustrating..

**Comment by alexwhb** [comment]
@4levels I ran into the same thing. Ref: #115

**Comment by 4levels** [comment]
Oh my, I should have been reading the closed issues as well!
@alexwhb Am I correct to assume you left the `@globalId` out for brevity?

Well, the error did go away, (i did change the `global_id_field` config to read `'id'`) but only after using `class` instead of `namespace`, like so: (my Image model acutally lives in the `app/Models/Image/` directory)

```graphql
type Image implements Node @model (class: "App\\Models\\Image\\Image") {
  id: ID! @globalId
  ...
}
```

Still, I'm not sure how this is helpful in any way as the query just returns the same globalId as result!  It does provide the correct value for `__typename`, but there's nothing more I can retrieve, so what's the point?  It's like requesting a node with id `xyz` just to get the `xyz` as reply (the one thing we do already know).  
So there currenly is no easy way to get a model by it's global id, right?  I could use a paginator with the `after` and `limit` filters, then get the result and use that in a new query using the `before` filter, but that's just insanity imho 

@chrissm79 changing the `global_id_field` in the config makes the `@rename` directive as you showed in #115 not even required as eg. @kikoseijo has pointed out

**Comment by alexwhb** [comment]
@4levels I'm not using `@globalId` in that context because it's not needed. I'm about 99% sure that directive is used for converting the globalId value back to a local id when you are using other directives that require the real model ID.

**Comment by 4levels** [comment]
Hi @alexwhb,

I was convinced the globalId was the 'Relay way' of getting a record (to update it's cache etc etc) and should be used instead of the database id attribute when consuming the graphql data.  I thought I don't need to expose the real database id at all when working with Relay as I can always use the globalId instead and this would ensure the records are always correctly referenced since the type is also included in it.  But now that the `node` query seems useless, (it doesn't even convert the globalId to the database id), I'm even more confused.

I'm surprised that you can get more fields from your model than I can.  As soon as I provide one of the fileds (eg. `filename`), I get the error `"Cannot query field \"filename\" on type \"Node\"."`

Time for me to re-think / re-educate myself about Relay I guess..

Regarding the `namespace` attribute provided to the `@model` directive: no matter what I enter there, the previous error persist (`Class 'App\\Models\\Image' not found` whilst I clearly specified `App\Models\Image\Image`) and only goes away when I specify the `class` attribute instead.  Maybe there's some hidden assumption somewhere that models HAVE to live in app/Models?

Thanks again for your swift and very helpfull replies!

FYI below are the schema and the queries i'm trying..
schema.graphql:
```graphql
type Image implements Node @model (namespace: "App\\Models\\Image\\Image"){
  id: ID! @globalId
  filename: String
  thumbnail: String
  rating: Int
  created_at: DateTime
}
type Query {
  images: [Image!]! @paginate(type: "relay", model: "App\\Models\\Image\\Image")
}
```
Graphql queries:
```graphql
query getImage {
  images (first: 2) {
    edges {
      node {
        id
        filename
        rating
      }
    }
  } 
  node (id: "SW1hZ2U6MTE3MQ==") {
    id
    __typename
  } 
}
```
which keeps resulting with the forementioned error message `Class 'App\\Models\\Image' not found`

**Comment by alexwhb** [comment]
@4levels You are totally right... the global ID is required for relay. That was my mistake in my previous answer. You should not be using the db ID's unless you have UUID's and even then... probibly not a good idea since you would not be able to use the node resolver, since it's doing a base64 encoding of your 'modelName:id' so it knows what model to resolve.

**Comment by hailwood** [comment]
Hey @4levels the important thing to note is that @alexwhb is using fragments which you **must** use if you're using the `node` interface

```gql
{
    node (id: "SW1hZ2U6MTE3MQ==") {
        id
        __typename
    } 

    fragment ImageFields on Image{
        id
        any
        fields
        specific
        to
        the
        image
        model
    }
}
```

**Comment by hailwood** [comment]
Ah try moving the fragment out of your main query 

```gql
{
  images (first: 2) {
    edges {
      node {
        id
        filename
        rating
      }
    }
  }

  node (id: "SW1hZ2U6MTE3MQ==") {
     ...ImageFields 
  } 
}

fragment ImageFields on Image{
    id
    any
    fields
    specific
    to
    the
    image
    model
}
```

**Comment by alexwhb** [comment]
@4levels Sorry to hear that man. I'll say from my experience with JS implementations it's not better IMO, but maybe your experience will be better. In regards to your namespaces... if you put this in your composer.json file: 

```json
    "psr-4": {
      "App\\": "app/",
      "Test\\": "tests/",
    }
```

you should be able to reference any of your classes by their path's.
so here's like the mapping: /app/Http/SomeControllerName turns into /App/Http/SomeControllerName
basically all that changes is your lowercase app dir turns into uppercase because of that PSR-4 mapping directive in your composer file. I hope that makes sense. And I'm also sorry I could not be of more help. :/ I know how that goes.

**Comment by kikoseijo** [comment]
@4levels  some tips:

the `type User @model {`already implements the NODE, you can see it just inspecting the endpoint with a tool like graphql playground or others..

Also, think that you can have your models saved in any folder structure you want, as I see its the worst problem you showing, for example you can have things inside `App/Models/MyGroup/MyModel` and the *namespace* can just be `App/Models/MyModel`, behind the scenes composer writes them out in a single file so, you don't worry where you save them. (Don't make things complicated until you able to dominate it, follow the natural `@flow`)

Hope this tips can make the picture a bit more clear...

**Comment by chrissm79** [comment]
@4levels Sorry for the delayed response! And sorry to hear about the struggles you were experiencing.. I can tell you that I walked away from PHP/GraphQL for about a year to work w/ Node because of how many tools were available, but I could never find a ORM as powerful as `Eloquent` which led to other frustrations (however, I'm glad I went down that route because it provided a path to v2.0 of Lighthouse!). 

From what I've gathered, it seems that you've resolved the majority of your issues and the final one remaining is in regards to the error message about the missing `_id` field. 

So the `Node` interface is defined like so:

```graphql
type Node {
    _id: ID!
}
```

This is a contract very similar to interfaces in PHP land where. But instead of describing what methods are available, a GraphQL interface provides a list of guaranteed fields. This means that your `Image` type should also include a `_id` field (if you leave the `global_id_field` set to default) and should look something like this (which is the way I choose to do things in my projects):

```graphql
type Image implements Node {
    # this will take the `id` of the model and pipe it through the `globalId` resolver
    _id: ID! @rename(attribute: "id") @globalId
    id: Int!
}
```

If you change the `global_id_field` to `id`, then you should be able to keep your `Image` type defined just as you have it since it has the `id` field is already set to `ID!`.

Hopefully that made sense 😄 But let me know if you have any other questions/issues!

**Comment by 4levels** [comment]
Hi @chrissm79,

Thanks for your reply and update instructions on how to tackle this.  As you guessed it already, I did manage to resolve it with help of the great people using lighthouse :+1:

**Comment by chrissm79** [comment]
Hey @4levels, are we okay to close this one or are you still having some issues? Let me know if you have any questions!
