### ISSUE TITLE
Same Model Relations

### ISSUE THREAD

**Issue by alexgomez88** [nuwave/lighthouse#1365]
**What problem does this feature proposal attempt to solve?**
When a model belongs to relation with the same model, the attribute become null

**Which possible solutions should be considered?**
I made a Directive that solve the problem but I think it should be an extension of BelongsTo:

```php
<?php

namespace App\GraphQL\Directives;

use Closure;
use GraphQL\Type\Definition\ResolveInfo;
use Nuwave\Lighthouse\Schema\Values\FieldValue;
use Nuwave\Lighthouse\Support\Contracts\Directive;
use Nuwave\Lighthouse\Support\Contracts\FieldMiddleware;
use Nuwave\Lighthouse\Support\Contracts\GraphQLContext;

class belongsToSameModelDirective implements Directive, FieldMiddleware
{
    public function name(): string
    {
        return 'belongsToSameModel';
    }
    
    public function handleField(FieldValue $fieldValue, Closure $next): FieldValue
    {

        $previousResolver = $fieldValue->getResolver();

        $wrappedResolver = function ($root, array $args, GraphQLContext $context, ResolveInfo $info) use ($previousResolver) {

            $result = $previousResolver($root, $args, $context, $info);

            return $result;
        };

        $fieldValue->setResolver($wrappedResolver);
        return $next($fieldValue);
    }
}
```

then we can use it at:
```graphql
type Task {
    id: ID!
    content: String!
    parent: Task @belongsToSameModel
}
```

Note: I know I just pass the model without process it but it works very well

**Comment by spawnia** [comment]
@alexgomez88 that directive does absolutely nothing, you can just remove it and your query will work fine, too.

I just added a test to verify that `@belongsTo` indeed works when models relate to themselves, see https://github.com/nuwave/lighthouse/commit/3d27a3ab120382e2ca5846d93f5f9430e3b9ff2a

Feel free to add a failing test case that reproduces the issue you have. Until then, i am going to assume that the issue is rooted within your model/table definition and not Lighthouse itself.
