### ISSUE TITLE
DefinedDirective deprecated without alternative

### ISSUE THREAD

**Issue by JasonTheAdams** [nuwave/lighthouse#1383]
**Describe the bug**

The `DefinedDirective` interface is used to provide a definition for a custom directive. Recently, though I can't tell when from the [releases](https://github.com/nuwave/lighthouse/releases), this interface has been deprecated, stating:
```php
/**
 * @deprecated will be integrated into
 * @see \Nuwave\Lighthouse\Support\Contracts\Directive
 */
```
This is confusing, as the `Directive` interface has also been deprecated. It looks like the `BaseDirective` abstract class now provides a default `name` method which can be overridden.

It doesn't appear to take the `definition` method into account in any way, however. So providing a `definition` method without using the `DefinedDirective` interface doesn't produce the definition when running `php artisan lighthouse:ide-helper`.

**Expected behavior/Solution**

I would expect the deprecation notice to reflect some sort of alternative as to how to maintain this functionality in the new means of doing so.

**Lighthouse Version**

v4.13.1

**Comment by lorado** [comment]
As far as I know, `DefinedDirective` was introduced to filter directives, to be sure, that generated directives IDE helper contains only well formed definitions. It was actually first solution, to provide automatically generated directive descriptions for all directives, also custom. So if you want `php artisan lighthouse:ide-helper` to take your directive into generated file, you have to implement that interface.
Anyway, it should be removed in v5, therefore all directives will be considered for generated file. So I guess on your side you would probably simply remove `implements DefinedDirective` from your directive, and let your `definition` method as is.

The `name` property - is a different topic. Earlier it was needed to get know at all, with which name your directive PHP Class is be used in SDL. It turned out, that it is only additional (duplicated) work. People should follow the naming convention anyway, like `FooBarDirective`, and the SDL name was always like `fooBar`, which can be sure autogenerated.

So to answer your question - you are right, there is no alternative for `DefinedDirective`, as the `definition` property will be (I guess for 99%) moved to `BaseDirective`, so simply continue to use it =)

> It doesn't appear to take the definition method into account in any way, however. So providing a definition method without using the DefinedDirective interface doesn't produce the definition when running php artisan lighthouse:ide-helper.

May be we should apply these changes soon. @spawnia, what do you mean?
