### ISSUE TITLE
Automatically resolve Connections

### ISSUE THREAD

**Issue by Zn4rK** [nuwave/lighthouse#14]
If I create a new connection and providing a [FQC](http://php.net/manual/en/migration55.new-features.php#migration55.new-features.class-name), It would be awesome if the `ConnectionRegistrar` checked if it was a class (class_exists) and tried to resolve it via the service container, before the instance is created.

```php
public function fields() {
    return [
        'maps' => GraphQL::connection(MapConnection::class)->field()
    ];
}
```

It would make it possible for us to utilize the Dependency Injection in the Connection, instead of using the helper-function `app` to pull in necessary services and such. 

Again, I would be happy to provide a PR for this.

**Comment by chrissm79** [comment]
@Zn4rK Originally, I had the connection registrar take in the name of the connection you wanted to create (i.e., `UserTasksConnection`). But after some refactoring, I passed the instance instead and just performed a `instanceof` check in the [ConnectionRegistrar](https://github.com/nuwave/lighthouse/blob/16ab1427e0d840d4e57243f514d7b013fc469b55/src/Schema/Registrars/ConnectionRegistrar.php#L80).

I didn't have the previous method documented, so I'd say it should be pretty safe to allow a `FQC`. If you want to provide a PR that would be great! Otherwise, I'll try to get this worked in soon. Thanks for the feedback!

**Comment by Zn4rK** [comment]
Sorry, I thought I was going to have more time this week. I think the ConnectionRegistrar is in need of a refactor generally.

I won't have time to look at this specific issue the next week, so If you manage to squeeze it in before me, go ahead. I'll keep you updated if I find the time.

**Comment by chrissm79** [comment]
With v2.0 you can use the `paginate` or `hasMany` directives with the `type` argument set to `relay` to auto-generate connections. Let me know if you experience any issues.
