### ISSUE TITLE
Cannot use blank types _ inside objects

### ISSUE THREAD

**Issue by v1narth** [nuwave/lighthouse#1401]
Directives like `@orderBy` and `@whereConditions` can accept a blank type defined by `_`, which is working perfectly in the queries root, but not inside an object.

Working:

``` bash
type Query {
    users(where: _ @whereConditions) : [User]
}
```

Not working:

``` bash
type Query {
    users(input: UsersQueryInput @spread) : [User]
}

Input UsersQueryInput {
    where: _ @whereConditions
}
```

Im not sure if its a bug, or it is intended, are there any reasons for it not to be implemented?

Version 4.13.1

**Comment by spawnia** [comment]
Categorizing this as a bug because the definition for `@whereConditions` indicates that this should work on both places: `ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION`.

Lighthouse applies a process we call *schema manipulation* for some directives, allowing them to transform the GraphQL AST: https://github.com/nuwave/lighthouse/blob/301930b356faa63da681d564cbef41c7d312f2aa/src/Schema/AST/ASTBuilder.php#L133-L137

The directives `@whereConditions` and `@orderBy` implement the [`ArgManipulator`](https://github.com/nuwave/lighthouse/blob/master/src/Support/Contracts/ArgManipulator.php) interface. This is only called when they are defined directly on the args of a field.

While there is a directive interface for definitions that are directly applied on types (e.g. `input Foo @example`), we currently have no mechanism for traversing down into the fields of `input` types and apply transformation there.

An implementation for this would entail:
- Adding a new interface `InputFieldManipulator`
- Add a method to `ASTBuilder` that applies it to `input` fields
- Implement the interface for the `ArgManipulator` directives where it makes sense

**Comment by BenHeimberg** [comment]
Thanks for the clarification and fix.

**Comment by BenHeimberg** [comment]
Also, there are ways of using nested where conditions?

**Comment by spawnia** [comment]
#1412 is nice, but does not solve the problem you were alluding to in this issue. I created #1417 as a follow up to track the usage of directives on input fields.

**Comment by v1narth** [comment]
Thanks!
