### ISSUE TITLE
Why was the @middlware directive considered deprecated?

### ISSUE THREAD

**Issue by wolfiton** [nuwave/lighthouse#1532]
HI,

If a directive becomes deprecated I would like to suggest writing in the documentation the **new replacement directive link** or the **reason for elimination**.
So everybody can understand the most important questions **WHY and HOW**.

WHY: Why does this directive become obsolete(deprecated)?

HOW: I need to know how to use the new directive that replaces the old one or I need to rethink my code to achieve what that directive did in a better way.

Also, I think that the middleware directive can be used to keep the integrity of data.

What do you mean?

We can't accept data only from the client especially when we are dealing with a user relation that needs to also be verified server-side.

Thanks

**Comment by spawnia** [comment]
https://github.com/nuwave/lighthouse/blob/master/UPGRADE.md#replace-middleware-with-guard-and-specialized-fieldmiddleware

**Comment by NickBourque** [comment]
There are completely valid use-cases for the `@middleware` directive, such as authenticating using something other than an `Authenticatable`. Guards can't handle this scenario, so by removing middleware, the ability to auth using a simple shared secret or basic auth has been removed. What was the harm in keeping `@middleware` and just adding `@guard` instead of completely replacing it?

**Comment by spawnia** [comment]
> it violates the boundary between HTTP and GraphQL request handling.
