### ISSUE TITLE
Directives on InputObjectType

### ISSUE THREAD

**Issue by dimitri-koenig** [nuwave/lighthouse#155]
Hi there

Argument directives don't work on input object types.

```graphql
type Mutation {
  updatePost(UpdatePostInput): Post
}

input UpdatePostInput {
  id: ID! @globalId
  title: String
}
```

Any idea why and how to solve it?

**Comment by spawnia** [comment]
Hey, i know exactly why! Currently, input object values are treated the same as fields.

I am currently reworking the directive system to follow the rules defined in the new specification, which explicitely lists all the possible locations for server side directives.

Currently, there is no easy fix - if you need your schema to work asap, you can put the arguments directly into the field and apply the directives there.

You can expect some changes regarding this topic in the next weeks. Directives for Input Objects are a big priority of mine as well, since i want to do some stuff with nested Inputs for complex mutations.

**Comment by dimitri-koenig** [comment]
Hm, I've digged into the code and could even apply the `@bcrypt` directive to a field, as an example. So even hacking around didn't work. Is it an issue of the underlying "graphql-php" package or lighthouse?

**Comment by spawnia** [comment]
You **could** apply most directives to anything, they just would not do anything. The workaround i was talking about would look like this:

````graphql
type Mutation {
  updatePost(
	id: ID! @globalId
	title: String
  ): Post
}
````

**Comment by dimitri-koenig** [comment]
Yeah, I know that would work but that's not a good solution in my case.

**Comment by spawnia** [comment]
There are some rather general issues that we have to solve before this. Once we have a solid foundation, we can go ahead and start to implement it. Have not started on it, you can expect things to happen roughly in the next two weeks.

**Comment by chrissm79** [comment]
@spawnia Actually, I believe this is a bit closer to your #184 issue... needing to allow and handle directives on an input definition's `InputValueDefinitionNode`. A input type's fields do not have a `resolve` function ([see here](http://webonyx.github.io/graphql-php/type-system/input-types/)). So if you wanted to place the `globalId` directive on an input type's `id` field, we have to do something like wrap the field's resolver w/ a function that transforms the input based on the directives defined. 

One possible solution would look like the `RuleFactory` where is traverses through a field's arguments looking for directives and uses the resolver defined or keeps the original input. That would need to happen on every field though (not just on the Mutation/Query types). I would be interested in seeing how big of an impact that has on execution time though.

**Comment by spawnia** [comment]
Tracking further progress of this in #184 

This will require breaking changes, so it is on the agenda for 3.x
