### ISSUE TITLE
Invalidate caches created by `@cache`

### ISSUE THREAD

**Issue by Rasool-deldar** [nuwave/lighthouse#1772]
Yes I want to help you develop a lighthouse.

**What problem does this feature proposal attempt to solve?**

To delete the cache

```graphql
extend type Query {
    categories: [Category!]! @all @cache(key: "categories") @softDeletes
    categories2: [Category!]! @all @cache @softDeletes # If the key is not filled, use categories2 itself by default categories2
}

extend type Mutation {
    createCategory(input: CategoryInput! @spread): Category! @trim @create @cache(key: "categoryAll", delete: true)
}
```

**Which possible solutions should be considered?**

When creating, editing and deleting (operations performed on the database), by adding a key and deleting it to @cache, we can delete it using cache. And save with the desired name using the key

**Comment by spawnia** [comment]
Currently, the `@cache` directive automatically generates a cache key that is quite dynamic and takes into account:
- authenticated users
- arguments passed to the field
- nesting of the field

See https://github.com/nuwave/lighthouse/blob/master/src/Schema/Values/CacheValue.php.

Because of that, invalidating the cache would indeed require naming the cache key. `@cache(key: "some-name")` seems like a suitable syntax for that.

I do not like the double use of `@cache`, let's use a separate directive for cache invalidation. I propose `@deleteCache(key: "some-name")`.

**Comment by AnthoniG** [comment]
How can we delete the cache in our code / resolver ?
For example, I have the Users query and it has the `@cache` directive on it.
However, when I create or edit a user I need to remove the cache, otherwise it keeps display stale values.

**Comment by spawnia** [comment]
@AnthoniG have you read [my previous comment](https://github.com/nuwave/lighthouse/issues/1772#issuecomment-810263185)?

**Comment by AnthoniG** [comment]
> Currently, the `@cache` directive automatically generates a cache key that is quite dynamic and takes into account:

You mean that one?

Yep read, just not fully understood it.
From that I take it I can work out the key and then use Laravels Cache Facade to forget it?

**Comment by spawnia** [comment]
No such feature exists as of now. I think we would need to implement one of two things (or both):
- add `key` argument to `@cache`, add a new directive to clear a cache by a static key
- add a new directive that can generate and clear a cache key that matches that of `@cache`

**Comment by spawnia** [comment]
Resolved by https://github.com/nuwave/lighthouse/pull/1931
