### ISSUE TITLE
@count directive makes a strange query

### ISSUE THREAD

**Issue by applyACS** [nuwave/lighthouse#1880]
I have a attribute defined on a model like this:

```graphql
type Table1 {
    agentViewedCount(pk: String @eq, agent_viewed: Boolean @eq): Int @count(relation: "rel_name")
}
````

this generates a query like this:

```sql
select "uuid",
(select count(*) from "rel_table" where "table1"."uuid" = "rel_table"."table1_id" and "pk" = 'key' and "agent_viewed" = 0) as "rel_name_count"
from "table1"`
```

Why does a select with uuid and the count?  I just want the count int value.
Just the second select should be enough.

Like this it takes a loong time, it's not efficient and cant not be used.

**Comment by spawnia** [comment]
Selecting the primary key of the parent is necessary, because a single query loads the count of all relations at once.

In the general case, this is far more efficient then sending multiple individual queries. I guess if there only is a single parent to load this query for, it would be slightly more optimal to only run the subselect, but it seems like those are marginal gains.

Laravel itself does not optimize for that, see https://github.com/laravel/framework/blob/e948bcb2d34152e27230def0ad48b24a1838229a/src/Illuminate/Database/Eloquent/Collection.php#L74. If you want this improved, try taking up the issue with them. Thank you
