### ISSUE TITLE
500 error for unknown types in variable definitions

### ISSUE THREAD

**Issue by andershagbard** [nuwave/lighthouse#1936]
**Describe the bug**

It returns 500 server error, if you are sending an unknown type in the orderByDirective.

**Expected behavior/Solution**

It should send some kind of GraphQL incorrect format response.

**Steps to reproduce**

1. Create a query which is using the `orderBy` directive
2. Define your query on the client side. E.g.:
```graphql
query(
  $page: Int!
  $first: Int!
  $orderBy: [UNKNOWN_TYPE!]
) {
  ...
```
3. Send query

**Output/Logs**

<details><summary>Click to expand</summary>

```
[2021-09-15 14:49:55] local.ERROR: Lighthouse failed while trying to load a type: OrdersOrderByOrderByClause

Make sure the type is present in your schema definition.
 {"userId":1,"exception":"[object] (Nuwave\\Lighthouse\\Exceptions\\DefinitionException(code: 0): Lighthouse failed while trying to load a type: UNKNOWN_TYPE

Make sure the type is present in your schema definition.
```

</details></br>

**Lighthouse Version**

5.23

**Comment by spawnia** [comment]
Thanks for the report. This issue applies more broadly to any unknown type in any variable definition, see https://github.com/nuwave/lighthouse/pull/1943 for reproduction.

I think this should be fixed upstream in https://github.com/webonyx/graphql-php. There is a validation rule in the GraphQL specification governing that variables must be input types, but it does not explicitly mention that the defined type must also exist: http://spec.graphql.org/draft/#sec-Variables-Are-Input-Types. I think because of this, no explicit test for proper handling of this case exists in the library.

**Comment by spawnia** [comment]
I opened a pull request against the reference implementation to add a validation step for this: https://github.com/graphql/graphql-js/pull/3282

**Comment by andershagbard** [comment]
Looks like this is solved upstream now
