### ISSUE TITLE
Consider using Visitor for AST manipulation?

### ISSUE THREAD

**Issue by vladar** [nuwave/lighthouse#194]
Hey guys,

I see you do some AST transforms on a schema, but you do it via plain AST modification. Just curious, have you tried using [Visitor](http://webonyx.github.io/graphql-php/reference/#graphqllanguagevisitor) for it?

I think it is the most convenient (and efficient) way to traverse and modify AST. If it doesn't work for you for some reason, maybe you can share some use cases when it didn't work? I'll look if we can cover them in the next version of the library.

**Comment by spawnia** [comment]
I did look into the visitor. It seems great for smaller transformations, i think it is too limited for us though.

You can take a look at the [PaginationManipulator](https://github.com/nuwave/lighthouse/blob/master/src/Schema/Directives/Fields/PaginationManipulator.php) to get a sense of the kinds of transformations we are doing. It involves both
modifying existing nodes, as well as adding completely new ones. In the future, we have planned to do some kind of CRUD schema generation from some basic type definitions.

Performance is not that big of an issue here, since we do all schema manipulation upfront and cache the result. Definitely open to improvements though!

**Comment by spawnia** [comment]
Is it true that when using the visitor, it is only possible to alter the current node and subnodes?

**Comment by chrissm79** [comment]
Hey @vladar! I think @spawnia pretty much nailed it on the head... Visitor seems to only allow us to manipulate the current node (and subnodes) that's being evaluated but we need to be able to create new nodes to add to the schema and it just seemed to be more logical to have all of that functionality in one place.

Would love to get your feedback though! We've had to do some hacks to introduce immutability on the DocumentAST and ensure we're replacing the correct type if it's an Extension definition (see [here](https://github.com/nuwave/lighthouse/blob/242b84a736bac36ba803574512440296a7715d6e/src/Schema/AST/DocumentAST.php#L72-L76) and [here](https://github.com/nuwave/lighthouse/blob/242b84a736bac36ba803574512440296a7715d6e/src/Schema/AST/DocumentAST.php#L293-L295)).

**Comment by vladar** [comment]
> Is it true that when using the visitor, it is only possible to alter the current node and subnodes?

Yes but since it visits all the nodes (unless you explicitly tell it to skip some sub-tree) you can modify anything. The typical approach is to collect the data you need on `enter` hook (of various node kinds) and then modify any nodes you need on `leave`. Adding nodes is a matter of editing the parent node.

> It seems great for smaller transformations, i think it is too limited for us though.

Technically it should allow AST transformations of any complexity (even tranformations to arbitrary non-AST structures), but I'll look at your Pagination example when I have a chance (probably on the week-end) and will try to re-implement it using Visitor for reference. Its an interesting challenge %)

**Comment by vladar** [comment]
FYI, I've built a simple repo to demonstrate how visitor works for something like `@paginate` directive: https://github.com/vladar/graphql-visitor-example

As I said, it collects required data when entering `field` and `directive` nodes. Then it will apply transformations using this data when leaving `field` node and add new types when leaving `document` node.

This is a rather simple thing to do for a visitor. Anyways, its primary usage is for performant AST traversal and modification, so if you are not concerned about performance - then it doesn't matter much which tool you use for it.

But still, keep the Visitor in mind, it is very powerful.

**Comment by spawnia** [comment]
@vladar thanks again for your involvement in this issue.

As we said, performance is not an issue for us when it comes to AST manipulation, as the result is cached.

I think the API we expose through directives to enable them to influence AST manipulations fits very well for our specific use-case, which is why i am going to close this issue.

Still, i will definitely keep the Visitor in mind. If we plan to do some larger manipulations on the whole schema, it might serve us well.
