### ISSUE TITLE
*Many relations return empty array instead of null

### ISSUE THREAD

**Issue by webard** [nuwave/lighthouse#1980]
Hi,
I don't know, maybe it is intentionally, but relations with many items, when are empty, returns `[]`. Relation with one item return `null`.
In my opinion it is not transparent to client. They need to check if value is null or is empty, instead of just checking is null.

**Expected behavior/Solution**

All types of relations shloud return `null` when they don't have any items.

**Steps to reproduce**

1. Create hasMany relation
2. Create hasOne relation
3. Run query on entity without any related data

**Example**

Look at parent and products.

<details><summary>Click to expand</summary>

```json
{
    "data": {
        "facets": {
            "data": [
                {
                    "id": "1",
                    "slug": "metal",
                    "parent": null,
                    "products": [],
                    "translation": {
                        "name": "Metal"
                    }
                }
            ]
        }
    }
}
```

</details></br>

**Lighthouse Version 5.26.0**

**Comment by lorado** [comment]
I disagree. AFAIK in Laravel you have the same behavior. For many relation you receive empty collection, for single relation you receive null. So it actually works as it should, in my opinion

**Comment by spawnia** [comment]
Indeed, this mirrors the native behaviour of Laravel, it would require extra work to change it. Such a change would incur massive breaking changes.

In our applications, we actually have a coding guidelines that GraphQL fields that return lists must always return non-nullable, non-sparse lists: `[T!]!`. This actually makes handling them quite easy on the client, since you can always iterate over them and never have to check for null.

> They need to check if value is null or is empty, instead of just checking is null.

With a nullable type, an empty list is still a possible result. The concept of a non-empty list is not enforceable through the GraphQL type system - actually, very few type systems in any programming language can express such a concept.

For those reasons, I am firmly convinced that we will stick with the current approach. If you are dead set on changing it, you could probably add a custom field middleware that converts empty iterables to null, but I would strongly advise against it.
