### ISSUE TITLE
Deduplicate database queries made through `@can`

### ISSUE THREAD

**Issue by baravak** [nuwave/lighthouse#1989]
**What problem does this feature proposal attempt to solve?**

Checking model-specific policies through `@can` causes duplicate database queries:
1. for the policy check
2. for resolving the result

Given the following field definitions:

```graphql
gift(id: ID! @eq): Gift! @can(ability: "view", query: true) @find
gift(id: ID! @eq): Gift! @can(ability: "view", find: "id") @find
```

Lighthouse will produce two identical database queries:

```sql
select * from `gifts` where `id` = ?
select * from `gifts` where `id` = ?
```

**Expected behavior/Solution**

It would be ideal if Lighthouse could detect scenarios where the queries will be identical and reuse the result of the first query, avoiding a redundant query.

**Comment by spawnia** [comment]
I reformulated the issue into a focused feature request.

I can only see deduplication happening reliably for the variant that uses `@can(query: true)`. The variant with `@can(find: "id")` might not work in all scenarios, since the field might have other arguments which are currently not considered in the policy check query.

This is a difficult problem to solve due to the implementation strategy of `@can` and `@find`. Both are directives which are decoupled from each other and run in separate phases.
