### ISSUE TITLE
Possibility to use @globalId in custom directives

### ISSUE THREAD

**Issue by jordyvandomselaar** [nuwave/lighthouse#212]
I'm writing a custom directive to use with ID, but how do I decode a globalId to use in my query?

I have this code:
```
 public function handleArgument(ArgumentValue $argument)
    {
        return $this->injectFilter(
            $argument,
            [
                'resolve' => function (Builder $builder, string $key, array $arguments) {
                    $value = $arguments[$key];

                    $field = \preg_replace('/_contains$/', '', $key);

                    return $builder->where($field, 'LIKE', "%$value%");
                },
            ]
        );
    }
```

`id_contains: ID @contains @globalId`

But it doesn't seem to work. Am I missing anything?

**Comment by chrissm79** [comment]
@jordyvandomselaar We're currently working on a solution for this (#155 and #184). TLDR; the problem is [field](http://webonyx.github.io/graphql-php/type-system/object-types/#field-arguments) and [input](http://webonyx.github.io/graphql-php/type-system/object-types/#field-arguments) arguments don't have a `resolve` function so we're going to have to create a utility that pre-processes arguments to transform them before they get to a resolver.

If you need to decode a `globalId` from inside a directive you can use the `Nuwave\Lighthouse\Support\Traits\HandlesGlobalId` trait and get the original id by calling `$this->decodeRelayId($encoded_value)`

**Comment by jordyvandomselaar** [comment]
Thank you for your answer! I'm gonna try this right away 🎉️

**Comment by jordyvandomselaar** [comment]
Works like a charm! Thanks again. I'll close this issue 👍️
