### ISSUE TITLE
Middleware directive was removed for no reason.

### ISSUE THREAD

**Issue by NickBourque** [nuwave/lighthouse#2204]
> it violates the boundary between HTTP and GraphQL request handling.

_Originally posted by @spawnia in https://github.com/nuwave/lighthouse/issues/1532#issuecomment-1239783346_

That's such a non-answer. [A GraphQL request is just an HTTP request at its core](https://graphql.org/learn/best-practices/#http). You're accomplishing nothing by revoking control from the people implementing this in their own projects. And you're not violating any fundamental law of the protocol by leaving the middleware directive in. There's also no conflict between the guard and middleware directives so replacing one with the other makes very little sense. 

Hiding behind the guise that this is some righteous purist fundamental rule that must be followed and locking further comments on a completely valid issue is whack.

**Comment by k0ka** [comment]
1. This directive was removed because it might change the HTTP layer that is used by the underlying GraphQL layer. So the library has to either re-evaluate the GraphQL layer (and end up with infinite recursion) or ignore possible changes (and end up with inconsistent results).
2. You can just copy that directive to your code and most probably it will work as is (but you will stumble upon issues why it was removed) - https://github.com/nuwave/lighthouse/blob/4.x/src/Schema/Directives/MiddlewareDirective.php
3. If you want to make some sort of your custom guard it's better to create a custom directive. It's very easy and more controllable.
4. You can ask further questions in [Slack](https://join.slack.com/t/lighthouse-php/shared_invite/zt-4sm280w1-wu21r94f3kLRRtBXRbXVfwl) or [Stack overflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse). We're checking them and answer quite fast.

**Comment by khanakia** [comment]
@k0ka I tried copy and paste it does give error on this line `handleField(FieldValue $fieldValue, Closure $next` does not match the definition becuase `Closure $next` does not existing anymore in new code

**Comment by k0ka** [comment]
It was changed in lighthouse v6, see https://github.com/nuwave/lighthouse/blob/master/UPGRADE.md#simplify-wrapping-resolvers-in-fieldmiddleware-directives
