### ISSUE TITLE
Illegal offset type in stateful authentication example

### ISSUE THREAD

**Issue by jacksontong** [nuwave/lighthouse#2210]
I've got this error when trying to follow the [satefull authentication example](https://lighthouse-php.com/5/security/authentication.html#stateful-authentication-example) with Sanctum

Here is the full stack trace https://pastebin.com/cn1SiGCU

I noticed that if I change `Auth::guard(config('sanctum.guard', 'web'))` to `Auth::guard('web')` then it fixes the issue

- Laravel version: 9.32
- Lighthouse version: 5.61
- Github repo https://github.com/jacksontong/laravel-graphql-example

**Comment by spawnia** [comment]
@dlindenkreuz I just checked and saw you authored this part of the docs. Indeed, the recommended approach for Sanctum is flawed due to Laravel defining Sanctum guards as an array - see https://github.com/laravel/laravel/blob/e87bfd60ed4ca30109aa73c4d23250c113fe75ff/config/sanctum.php#L36

I proposed a fix for this, please review https://github.com/nuwave/lighthouse/pull/2211

**Comment by spawnia** [comment]
The docs are now fixed.
