### ISSUE TITLE
[Bug] Unit tests on Travis doesn't fail when running empty test

### ISSUE THREAD

**Issue by olivernybroe** [nuwave/lighthouse#238]
**Describe the bug**
When running unit tests with Travis it does not fail if the test case does not perform any assertions

**Expected behavior**
Fails if no assertions has been passed.

**Comment by spawnia** [comment]
That is the expected behaviour, as detailed in the PHPUnit docs https://phpunit.de/manual/6.5/en/incomplete-and-skipped-tests.html

It is considered best practice to mark such tests as incomplete, the link above also contains an example for that.

If you find such incomplete tests, i would be happy about a PR that clearly marks them as such.
