### ISSUE TITLE
Simplify exposing root `Query` type in mutation responses

### ISSUE THREAD

**Issue by jaulz** [nuwave/lighthouse#2380]
**What problem does this feature proposal attempt to solve?**

It would be great if there would be a way to resolve the `Query` type again in mutation responses like it's described here:
https://graphql-rules.com/rules/mutation-payload-query

Unfortunately, I did not find a nice way how this could be achieved via a custom directive but maybe I was looking in the wrong spots.

**Which possible solutions should be considered?**

Either there could be a pre-delivered `@query` directive that can be used on fields without any extra effort or otherwise a simple helper would be great that would allow developers to implement it by themselves.

**Comment by k0ka** [comment]
Not sure if it is written somewhere in docs. Query is resolved automatically. Like this:

```graphql
type MutationResult {
    result: Boolean!
    query: Query!
}
```

in resolver:
```php
public function __invoke($_, array $args): array
{
    return [
        'result' => true,
    ];
}
```

**Comment by spawnia** [comment]
There is a solution available, but I think it is quite unintuitive and somewhat cumbersome. Basically what @k0ka is doing with his solution is just provide any non-null value in order to allow the nested field resolution to continue with `query: Query`. Perhaps we can just change the default resolver for all fields that return the root `Query` type to always return `true` and thus allow for this propagation?

One more thing that I could see being useful would actually involve a custom directive: exposing the root `Query` type on mutations that use build-in directives such as `@create`. Perhaps something like this in the schema:

```graphql
type Mutation {
  createFoo(input: CreateFooInput! @spread): Foo! @create @exposeQuery
}
```

The `@exposeQuery` directive would transform the schema definition by introducing an intermediary type and automatically transform the execution result to fit it. The final schema would look like this:

```graphql
type Mutation {
  createFoo(input: CreateFooInput!): CreateFooResult!
}

type CreateFooResult {
  result: Foo!
  query: Query!
}
```

**Comment by spawnia** [comment]
Please review https://github.com/nuwave/lighthouse/pull/2384. Do you think we should document this pattern or is it enough that it *just works™*?

**Comment by jaulz** [comment]
Nice, that would make it much more easier! 

Regarding `@exposeQuery` directive: I like the idea and this is exactly what I do right now in my custom `@payload` directive to ensure that the result of a mutation always has the same structure (e.g., I also have fields for `status` and `messages`). Maybe I am wrong but quite often I read that `Payload` is the name of the output of a GraphQL mutation so maybe it makes sense to also name the new directive `@payload` and use `Payload` as a suffix?

**Comment by spawnia** [comment]
I think the term `Payload` is incorrect for the wrapper type, since it achieves the exact opposite of what a *payload* is supposed to do or be - [differentiate the protocal overhead from the actual data](https://en.wikipedia.org/wiki/Payload_(computing)). I could see calling the wrapper type `*Result` and nest the value returned from the mutation itself under a field `payload`.

**Comment by jaulz** [comment]
Thank god I am not the only one who found it confusing to call it `Payload`...

**Comment by spawnia** [comment]
I am closing this issue for now, as https://github.com/nuwave/lighthouse/pull/2384 was merged and released with https://github.com/nuwave/lighthouse/releases/tag/v6.7.0. I am open for further improvements through a directive, but we can discuss those in a pull request.
