### ISSUE TITLE
Issue with validators on query endpoints

### ISSUE THREAD

**Issue by LepinzanB** [nuwave/lighthouse#2404]
**Describe the bug**

I have a problem with  the validators on queries. 
I used directive @all where I have  a builder and the class of the builder. When I run the query first time enter Builder class and then Validator. 

**Expected behavior/Solution**

**Steps to reproduce**

1. Check the rules from Validator
2. If it's all good run the Builder

**Output/Logs**

<details><summary>Click to expand</summary>

```
 extend type Query @guard {
    users(filters: UserFilterInput): [User!]! @can(ability: "viewAny", injectArgs: true) @all(builder: "MyClass")
}

input UserFilterInput @validator {
    layout_target: platformTypes!
}

layout_target -> is required in my validator rules
```
</details></br>

**Lighthouse Version**

v5.71.0

**Comment by spawnia** [comment]
I do not understand what your issue is. Please check the tests for `@validator` that show how it works, perhaps add a failing test case through a pull request that illustrates your use case - see https://github.com/nuwave/lighthouse/blob/master/tests/Integration/Validation/ValidatorDirectiveTest.php.
