### ISSUE TITLE
Also use flatten (nested queries with input types) for @paginate and @all directive

### ISSUE THREAD

**Issue by maarten00** [nuwave/lighthouse#249]
**Is your feature request related to a problem? Please describe.**
I want to use input types in my `@all` and `@paginate` directives.

**Describe the solution you'd like**
I want to use the `flatten: true` argument from #207 in my `@paginate` and `@all` directive. I tried using it, but it seems that is not yet supported. It would be awesome if I can use the same logic here.

My schema is as follows:
```
type Query {
    addresses(input: whereAddressesInput): [Address]! @all(model: "Address", flatten: true)
}

input whereAddressesInput {String @eq country_code_not: String @not country_code_in: String @in country_code_not_in: String @not_in country_code_lt: String @lt country_code_lte: String @lte country_code_gt: String @gt country_code_gte: String @gte country_code_contains: String @contains country_code_not_contains: String @not_contains country_code_starts_with: String @starts_with country_code_not_starts_with: String @not_starts_with country_code_ends_with: String }
```

_I have shortened the input type in this example, but it should give an idea of how big it actually is when you have 10 columns in your table._

**Describe alternatives you've considered**
Using multiple arguments, but that quicky gets messy when you want to provide a big set of arguments possibilities for every column.

**Additional context**
I have actually tried adding the implementation as in #207 to the directive code, but it appears it's not as easy as adding just this code to the directive:
```
$flatten = $this->directiveArgValue('flatten', false);
$args = $flatten ? reset($args) : $args;
```

@spawnia If you could give some pointers I would be happy to give this a go myself, but for now I'm not comfortable enough with the codebase to know what I'm doing.

**Comment by spawnia** [comment]
Hey @maarten00 this issue has been dormant for a bit now, i just recently thought about this.

The single InputObject pattern is a very common one, even more so with Relay, which requires it for all mutations. Adding `flatten: true` to a sizeable portion of the fields in a schema seems a bit tedious, so i figured we could do some magic here 🌈 

How about all fields that have exactly a single argument that is called `input` and is also an InputObject get flattened by default? We can expose a helper that makes adding this functionality to a directive a one-liner.

As you have noticed, flattening is not necessarily sufficient for making the query directives (like `@eq`, `@in`...) work for InputObjects. This correlates with a long standing issue we have with how InputObjects are treated in general (in my opinion: wrong), see #184 for additional discussion. That is something that should be fixed, but might have to wait a bit since it would break the internal API's quite a bit.

As an alternative to hardcoding conditions in the server side schema, @yaquawa and me have been exploring options on how to enable the client to control the Query better. I would value your opinion over at #312

**Comment by spawnia** [comment]
@chrissm79 @maarten00 @olivernybroe @yaquawa 

Opinions on my suggestion? Too much magic? Too little? 🤔

**Comment by maarten00** [comment]
The long term solution sounds like a great idea to me!
I haven't had a chance to fully read through #312, but I'll see if I can give some feedback tonight. Seems like a good idea so far!

**Comment by chrissm79** [comment]
@spawnia A bit too much magic, however, some sort of config option here would be great (i.e., `flatten_input` => `true`), otherwise the `flatten: true` argument on the directive would be the way to go... a bit tedious (if you don't set the config option to `true`) but at least you have full control over your input field(s).

**Comment by yaquawa** [comment]
> How about all fields that have exactly a single argument that is called input and is also an InputObject get flattened by default? We can expose a helper that makes adding this functionality to a directive a one-liner.

@spawnia I would like vote for this one. Simple is the best, magic is good for me.

**Comment by spawnia** [comment]
@chrissm79 I would not flatten input fields for custom resolver, but only for Lighthouse internal directives. If the user wants that, they can utilize a helper that flattens it for them if they want.

As it stands, internal directives do not work with InputObjects, unless specifically told so by `flatten: true`, so i figured we might as well automate the discovery.

**Comment by chrissm79** [comment]
@spawnia Which internal directives? If we're talking about `@paginate`, `@all` or others then we need a way to opt out/in of flattening (either by a config option or per directive).

**Comment by spawnia** [comment]
For example the following:

```graphql
input Foo {
  bar: String
}

type Mutation {
  createBaz(input: Foo): Baz @create
}
```

This will only work if the input object is flattened, so i do not see why there needs to be any choice involved.

**Comment by maarten00** [comment]
To be honest, that is exactly what I was expecting when I first tried to use input fields. I don't think there are any use cases for input fields where you don't want them flattened.

**Comment by chrissm79** [comment]
@spawnia Gotcha, I got stuck on a different implementation that really doesn't even apply 👍

**Comment by spawnia** [comment]
@maarten00 to come back to your original point, in the particular case of `@paginate` or `@all` this will be hard to solve.

I see you are expecting the query directives of the InputObject to get applied to the field you are using it on. The problem here is that the InputObject is not guaranteed to be part of this field, it might also be used in any other field or even as a nested InputObjectValue.

If your Query is so complex that you need an InputObject, i think you are better off with something like #312 once we have that figured out.

So my plan is:
- Generalize and automate flattening for the directive it makes sense on
- Leave `@all` and `@paginate` as is. You may pass a custom builder to `@paginate` as pf #326 and may be able to enjoy rich client side querying as in #312

**Comment by SirLamer** [comment]
> How about all fields that have exactly a single argument that is called `input` and is also an InputObject get flattened by default? We can expose a helper that makes adding this functionality to a directive a one-liner.

As a heads-up, there is a high risk of collision of attribute names if all input objects are flattened. For example if a mutation expects two input objects for different sets of data and both include the attribute "name" they would collide upon flattening.
