### ISSUE TITLE
Performance issues since v2.1.1 when using large lists

### ISSUE THREAD

**Issue by Yurookai** [nuwave/lighthouse#254]
**Describe the bug**
After updating my project to the latest version of Lighthouse, a certain query which returns quite a large dataset became a fair bit slower.

When rolling back to v2.1, the time it took for the query was faster. I've tried to locate the issue, but unfortunately didn't find it. What has changed that could cause this, or is it a feature?

<img width="805" alt="Timing between versions" src="https://user-images.githubusercontent.com/7791196/43961111-580b9300-9cb4-11e8-8139-681266ef14b6.png">

**Resolver**
```php
public function resolve()
{
    $range = [
        $from = Carbon::now(), 
        $to = Carbon::now()->addYear(2),
    ];

    $date = $from->format('Y-m-d');

    while (strtotime($date) <= $to->timestamp) {
        $date = date(
            'Y-m-d', strtotime('+1 day', strtotime($date))
        );

        $dates[] = [
            'date' => $date,
            'arrival' => false,
            'departure' => false,
        ];
    }
        
    return $dates ?? [];
}
```

**Schema**
```graphql
type Query {
  availability: [Date!]
}

type Date {
  date: String
  arrival: Boolean
  departure: Boolean
}
```

**Environment**
Lighthouse Version: v2.1 and v2.1.1
Laravel Version: 5.6
PHP Version: 7.2

**Comment by spawnia** [comment]
> is it a feature?

Yeah, our current times are just way to stressful. Gotta give the user some time to relax.

In all seriousness though, thanks for your report. Did you activate Schema caching in the newest version?

**Comment by Yurookai** [comment]
Haha, thought so.

I enabled caching, and it went back to normal. Its still not as fast as just a normal json response, but I can get around that by using pagination.

**Comment by spawnia** [comment]
Yeah, the selling point of GraphQL is not that it is blazingly fast for simple responses. You do get some pretty nice benefits when you get into more complex queries by eliminating the need for extra round trips.

I am glad that caching solved your issue. Since v2.1 Lighthouse has shifted more heavily towards leaning on the schema cache. We do some pretty extensive manipulation of the schema upfront, way to much work to do on every single request. I have been having some performance issues with very large schemas, so you can expect some more work on that in the next few weeks.

Can we close this issue as of now?

**Comment by Yurookai** [comment]
Alright, thanks for the info!
