### ISSUE TITLE
More validation methods in validation class

### ISSUE THREAD

**Issue by abbasudo** [nuwave/lighthouse#2605]
Hello, Thanks for your awesome package.
It would be better if we had more options in validation classes like authorize and prepareForValidation in [laravels validation](https://laravel.com/docs/11.x/validation#preparing-input-for-validation)

```php
/**
 * Determine if the user is authorized to make this request.
 */
public function authorize(): bool
{
    return true;
}
```

```php
use Illuminate\Support\Str;
 
/**
 * Prepare the data for validation.
 */
protected function prepareForValidation(): void
{
    $this->merge([
        'slug' => Str::slug($this->slug),
    ]);
}
```

Sometimes I had to write some extra logic for validation currently in the lighthouse I have to write validation logic into the mutation class.

**Comment by spawnia** [comment]
Lighthouse validation works by gathering validation rules from many different sources, such as validation classes and `@rules`. Because nested inputs can be highly dynamic, we don't operate under the same model as Laravel form validation.

Also, I believe that transforming incoming arguments and authorization are separate concerns. Lighthouse does have functionality for it.
