### ISSUE TITLE
GraphQLController@query trigger a user error when not auth

### ISSUE THREAD

**Issue by alert888** [nuwave/lighthouse#295]
**Describe the bug**

GraphQLController@query trigger a user error when not auth

**Output/Logs**

```
Argument 2 passed to Nuwave\\Lighthouse\\Schema\\Context::__construct() must be an instance of Illuminate\\Foundation\\Auth\\User, null given, called in /workspace/Php/lighthouse/src/Support/Http/Controllers/GraphQLController.php on line 45"
```

**Environment**

Lighthouse Version: master
Laravel Version: 5.6
PHP Version: 7.1.20

The GraphQLController@query function:
```php
    public function query(Request $request)
    {
        $query = $request->input('query');
        $variables = $request->input('variables');

        if (is_string($variables)) {
            $variables = json_decode($variables, true);
        }
        return response(
            graphql()->execute(
                $query,
                #look here!!!!!
                new Context($request, app('auth')->user()),
                $variables
            )
        );
    }
```

#282

**Comment by spawnia** [comment]
Have a fix for that lined up, did not consider unauthenticated routes. Hang tight, will push the fix in a few hours

**Comment by paulrees** [comment]
#### Environment

Lighthouse Version: master
Laravel Version: 5.6
PHP Version: 7.1

Hey guys - noticed this issue too yesterday so thanks for fixing so quickly! However I'm now getting a similar error with a User being passed to Context - 

`Argument 2 passed to Nuwave\Lighthouse\Schema\Context::__construct() must be an instance of Illuminate\Foundation\Auth\User or null, instance of App\Http\Users\Models\User given`

It looks like my actual User model is somehow being passed instead of Auth::user() - my AuthServiceProvider.php validates a JWT token and returns a User:

`return User::where('id', $credentials->user->id)->first();`

Can you see if I'm doing something weird/wrong here?!

**Comment by alert888** [comment]
your User Mode must extend of  `Illuminate\Foundation\Auth\User`

the code look like:
```php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;
class User extends Authenticatable
{
    use Notifiable,HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

**Comment by paulrees** [comment]
Thanks for the help! Am I right in thinking that would work just for Laravel - I'm using Lumen which doesn't have `Illuminate\Foundation\Auth\User` so will have a look to see what I can do instead.

**Comment by spawnia** [comment]
It does not? What does the `Auth::user()` facade return then?

**Comment by spawnia** [comment]
I would be fine with that, go ahead.
