### ISSUE TITLE
Description displays incorrectly

### ISSUE THREAD

**Issue by yaquawa** [nuwave/lighthouse#297]
For some reasons, the description looks like this😂
(I'm using the `dev-master` ver.)

![image](http://i.imgur.com/fQXsOSn.png)

**Comment by jandro935** [comment]
Same problem !! 👍

**Comment by spawnia** [comment]
This has to do with the [new description syntax](http://facebook.github.io/graphql/June2018/#sec-Descriptions).

Apparently, webonyx/graphql-php only implemented one half of it correctly - the parsing. Schema printing and introspection are buggy. While slightly ugly, this is not unusable, so i tend to just wait for a fix, which will possibly come in their `0.13`

**Comment by nob** [comment]
@spawnia Actually, this is unusable for Japanese description. Multi-byte characters, like Japanese (Probably Chinese, Korean as well ), are not even parsed correctly.
```
enum productStatus {
  """
  登録済み
  """
  REGISTERED @enum(value: 0)

  """
  レンタル可能
  """
  AVAILABLE @enum(value: 1)

  """
  レンタル中
  """
  RENTED @enum(value: 2)

  """
  クリーニング中
  """
  CLEANING @enum(value: 3)
}
```

These descriptions looks like this in GraphQL-Playground.
![screen shot on 2018-09-18 at 20_02_18](https://user-images.githubusercontent.com/114777/45683580-07266e80-bb7f-11e8-866c-df150bee2a1f.png)

**Comment by spawnia** [comment]
@nob that surely is unfortunate. If you can come up with a fix, i am willing to accept a PR. If not, i will stick to waiting for the upstream library to fix this.

**Comment by nob** [comment]
I start using Lighthouse few days ago and have used [Folkloreatelier/laravel-graphql](https://github.com/Folkloreatelier/laravel-graphql). 
I'm not sure I can figure it out.. but just wondering why laravel-graphql is able to print those descriptions correctly in GraphQL-Playground, even with Japanese description, it also use webonyx/graphql-php inside it's package...
```
class addCreditCard extends Mutation
{
    protected $attributes = [
        'name' => 'addCreditCard',
        'description' => 'ユーザのクレジットカード情報を追加'
    ];

....
```

![screen shot on 2018-09-18 at 23_13_47](https://user-images.githubusercontent.com/114777/45693803-d81cf680-bb98-11e8-8c1e-92ac38c303c4.png)

Is that because laravel-graphql doesn't directly parse schema.graphql file?

**Comment by spawnia** [comment]
Just a quick update: I realized the bug was on our side after all. Working on the fix at the moment.

I noticed that we do not pass descriptions for arguments, so i am reworking that as well. Stay tuned!
