### ISSUE TITLE
Hacktoberfest 2018

### ISSUE THREAD

**Issue by morpheus7CS** [nuwave/lighthouse#377]
Hey guys,

a lot of us are participating in the Hacktoberfest, so I was wondering if you could share a few things where you'd need help, not just in this repo, but also in lighthouse-docs or if lighthouse-example needs to be updated to the new version and have the features showcased?

Thanks & keep on the good work!
g

**Comment by spawnia** [comment]
In terms of the docs, additional guides and more detailed descriptions are always welcome. I am not a big fan of example projects, as they tend to get outdated - i would much rather see an actual, living project that uses Lighthouse and is Open Source. Will happily include that in the Docs as well.

I think #312 should be a pretty interesting one to hack on, since it is currently a wide open field. Feel free to hit me up for further discussion about it.

Apart from that, #77 #100 #99 #371 are also features that can stand on their own and deserve some love.
