### ISSUE TITLE
@paginate directive does not use namespace defined in @group

### ISSUE THREAD

**Issue by jeroenpf** [nuwave/lighthouse#418]
**Describe the bug**

When a namespace is defined in the `@group` directive, this namespace is not used to locate a custom builder class in the paginate directive. When you have a custom builder for pagination, you need to specify the full class path.

See schema example below.

**Expected behavior**

In my opinion, the expected behavior here is that the namespace is also applied to the paginate directive. Currently it only uses the namespace defined in the `lighthouse.namespaces.models` config.
I would expect this to work in a similar fashion as `@field(resolver: "Blog@posts")` that finds the class and method inside the @group namespace.

**Schema**

```graphql
extend type Query @group(namespace: "App\\GraphQL\\Resolvers") {
    posts: [Post!]! @paginate(builder: "Blog@posts")
}
```

**Output/Logs**

```
No class 'Blog' was found for directive 'paginate` is returned
```

**Environment**

Lighthouse Version: 10f357f98bfc86683490864129a2576e496fc4ed
Laravel Version: 5.6
PHP Version: 7.2.4

**Additional context**

https://github.com/nuwave/lighthouse/blob/10f357f98bfc86683490864129a2576e496fc4ed/src/Schema/Directives/Fields/PaginateDirective.php#L187-L189

**Comment by robsontenorio** [comment]
I agree that `@paginate(builder: “Class@method”)`,  if possible, should work for default namespaces (lighthouse.php). 

Much more cleaner.

**Comment by yaquawa** [comment]
Me too expect `namespace` in `@group` should always take priority of the one in the config file.

I think this behavior will confuse new comers to Lighthouse.
So if it's going to keep as is, add some additional description doc for this special case would be nice.

**Comment by zhuzhichao** [comment]
Me too expect namespace in @group should always take priority of the one in the config file.

I has been confused by the behavior, until I saw the source code. The namespace only works for `field` and `complexity`. If I create some directives, the namespace will not work well.

And I noticed `GroupDirective` has been deprecated since 2018/6/13 by @spawnia . I want to know some changes of the directive in the next version.

**Comment by spawnia** [comment]
We are about to remove `@group` in favour of `@namespace` in the next major version.
Because of this, i am not going to change the behaviour of `@group` anymore - it will be a wasted effort which might break something.

The new `@namespace` directive will allow you to specify explicitely for which other directives the namespace change should apply.
