### ISSUE TITLE
Lumen support

### ISSUE THREAD

**Issue by alfaproject** [nuwave/lighthouse#54]
This is exactly the kind of library that should be used on a small framework. All you really need is some routing and GraphQL magic.

With that said, is there any particular reason you are using Laravel only features like the router?

**Comment by 4levels** [comment]
Hi,

I'm also trying to get this running on a bare Lumen installation, but so far I'm not getting to the point where I can use the graphiql interface.
I already did refactor some minor things (since Lumen has a slightly different approach on service providers and configuration) and since I don't want to use Facades alltogether (IMO facades are userland tools, not library tools).

@kikoseijo Can you elaborate on this? I'm sure you've managed to get this working in Lumen ;-)

@chrissm79 As soon as I have managed to get this running, I'll document and PR my changes so you can evaluate as well.  Thanks again for this amazing project!

Kind regards,

Erik

**Comment by chrissm79** [comment]
@4levels That would be awesome! I haven't used Lumen for projects myself but I completely understand the use case/benefits here and would be more than happy to merge a PR for it!

**Comment by kikoseijo** [comment]
@4levels here you are:

https://github.com/kikoseijo/lumen-lighthouse-graphql

Its working for me, you must think that the endpoint its /graphql and uses `POST`

right now whats missing its the auth() helper method, does not comes with Lumen, ill provide a solution for this latter on.

Lumen does not have route:list either, and its hard to know.

**Comment by deltace** [comment]
@kikoseijo  : thank you for your help and for this library which is now available for lumen.  I will test your graphql library now. Waiting for new releases ...

**Comment by 4levels** [comment]
Hi @kikoseijo,

Thanks a million for your example repo!
I did however notice that this requires your ksoft/klaravel package but since I don't need any scaffolding nor crud in the browser, I left it out in my own repo.

However I seem to be running into issues with this: when I try to run the login mutation, I keep getting the following error: 
```
"errors": [
    {
      "message": "Trying to get property of non-object",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
```

Further investigation shows that it seems related to a Directive call, this is what shows up in the lumen.log file (truncated for brevity):
```
[2018-04-11 13:25:09] production.INFO: GraphQL Error: {"code":0,"message":"Trying to get property of non-object","trace":"#0 vendor/webonyx/graphql-php/src/Executor/Executor.php(855): GraphQL\\Error\\Error::createLocatedError(Object(ErrorException), Object(ArrayObject), Array)
#1 vendor/webonyx/graphql-php/src/Executor/Executor.php(799): GraphQL\\Executor\\Executor->completeValueWithLocatedError(Object(GraphQL\\Type\\Definition\\ObjectType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Object(ErrorException))
#2 vendor/webonyx/graphql-php/src/Executor/Executor.php(721): GraphQL\\Executor\\Executor->completeValueCatchingError(Object(GraphQL\\Type\\Definition\\ObjectType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Object(ErrorException))
#3 vendor/webonyx/graphql-php/src/Executor/Executor.php(398): GraphQL\\Executor\\Executor->resolveField(Object(GraphQL\\Type\\Definition\\ObjectType), NULL, Object(ArrayObject), Array)
#4 vendor/webonyx/graphql-php/src/Executor/Executor.php(415): GraphQL\\Executor\\Executor->GraphQL\\Executor\\{closure}(Array, 'login', Array, Object(GraphQL\\Type\\Definition\\ObjectType), NULL, Object(ArrayObject))
#5 vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromise.php(135): GraphQL\\Executor\\Executor->GraphQL\\Executor\\{closure}(Array)
#6 vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromise.php(35): GraphQL\\Executor\\Promise\\Adapter\\SyncPromise->GraphQL\\Executor\\Promise\\Adapter\\{closure}()
#7 vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromiseAdapter.php(140): GraphQL\\Executor\\Promise\\Adapter\\SyncPromise::runQueue()
#8 vendor/webonyx/graphql-php/src/GraphQL.php(236): GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter->wait(Object(GraphQL\\Executor\\Promise\\Promise))
#9 vendor/nuwave/lighthouse/src/GraphQL.php(122): GraphQL\\GraphQL::executeAndReturnResult(Object(GraphQL\\Type\\Schema), 'mutation loginM...', NULL, Object(Nuwave\\Lighthouse\\Schema\\Context), NULL)
#10 vendor/nuwave/lighthouse/src/GraphQL.php(81): Nuwave\\Lighthouse\\GraphQL->queryAndReturnResult('mutation loginM...', Object(Nuwave\\Lighthouse\\Schema\\Context), NULL, NULL)
#11 vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php(44): Nuwave\\Lighthouse\\GraphQL->execute('mutation loginM...', Object(Nuwave\\Lighthouse\\Schema\\Context), NULL)
#12 [internal function]: Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController->query(Object(Illuminate\\Http\\Request))
...
```

So I'm not really sure where to digg, is this Lighthouse related or are there still underlying Lumen issues?
I have to add that I'm getting this error with and without facades..

Please find also my composer require section below
@chrissm79 is it possible to use the master branch? Or should I stick to the v2 (beta-xx) branch? I'm using the master branch currently from my fork of your repo..

```
    "require": {
        "php": ">=7.1.3",
        "laravel/lumen-framework": "5.6.*",
        "vlucas/phpdotenv": "~2.2",
        "nuwave/lighthouse": "dev-master",
        "predis/predis": "^1.1",
        "illuminate/redis": "^5.6",
        "laravel/passport": "^6.0",
        "dusterio/lumen-passport": "^0.2.6",
        "nordsoftware/lumen-cors": "^2.2"
    },
```

**Comment by kikoseijo** [comment]
Check out your passport keys, client and also ill look into the model class should extends from hasApitokens.

I can look at it latter if you cant figure it out.

**Comment by kikoseijo** [comment]
Haha, just realised, move to master now, yes.

Dev-master has a validation feature directive as beta.

**Comment by 4levels** [comment]
Hi @kikoseijo,

thanks for the quick follow up.
You pointed me in the right direction.  Let me explain:
I'm used to using the password grant using a client with credentials that I add to the request so the client_id & client_secret are never passed via public requests.

As soon as I enabled the personal access client grant by simply running passport:install again, everything started working!

Thanks again for your help!

Kind regards,

Erik

**Comment by 4levels** [comment]
To anyone reading this:
see this issue: #85 and this PR #78

**Comment by 4levels** [comment]
@alfaproject Please close this issue if the latest master branch fixes the support for Lumen.

**Comment by alfaproject** [comment]
I would prefer if someone else can test and close because I’m not working in the project that led me here. It would be unfair if I close it without testing.

**Comment by 4levels** [comment]
Hi @chrissm79,

I think it's safe to close this issue.  I'm actively using your latest version with the merged changes for Lumen support etc and you were able to run the tests successfully..

**Comment by chrissm79** [comment]
Thanks for testing @4levels!
