### ISSUE TITLE
Update at feb 2018

### ISSUE THREAD

**Issue by kikoseijo** [nuwave/lighthouse#64]
Hi there,

How we getting on this project, seems its been left aside from here.

Looking for Relay, as the [Folkloreatelier/laravel-graphql](https://github.com/Folkloreatelier/laravel-graphql) seems very active and I have been using it, Relay does not seem to be their focus.

I know that some of you are moving to Typescript and the lovely async functions, probably looking for the subscriptions, but ill like to continue using Laravel.

Any comments will be gratefully appreciated.

**Comment by hailwood** [comment]
As far as I am aware, the maintainer has moved to adonisJS and is no longer maintaining this package.

**Comment by kikoseijo** [comment]
Thank you @hailwood, I know you are working with the one mentioned above.

What are the features this package its missing? I know subscriptions are not posible due to PHP limitations.

@chrissm79 you think this package can go live? you nearly finished a super cool Documentation page. Whats missing? did you focus more on Relay?

Best regards,
Kiko Seijo.

**Comment by hailwood** [comment]
Actually @chrissm79 was working on subscriptions and I believe got them working using a 3rd party socket provider for the realtime needs.

In the end I'm not sure this package is missing anything, but there were a few issues that needed to be resolved, I moved away from the GraphQL packages for a while, and when I came back this one was unmaintained as such I went with the most popular option.

If you're already using this package, you can likely go to production with it, but I wouldn't want to try upgrading Laravel.

**Comment by kikoseijo** [comment]
Right now, using my forked version of laravel-graphql, I just upgraded the relay branch to be even with the latest commits.

Just trying to settle with the right package before take it to production, thats the reason keep asking about this and that. ;ost people going with Apollo and Graphcool sort of wrappers and not many interested in a Pure Relay perspective.

This is repo im using: (its relay branch)
https://github.com/kikoseijo/laravel-graphql

**Comment by chrissm79** [comment]
@kikoseijo Thanks for your interest in the package! And my apologizes for not being active in it's development lately. 

Back when I started development I was working on a project that relied on GraphQL to power it's mobile app. Since then, every additional project has been written in NodeJS, and therefore my focus had to shift to support the products I was currently working on.

I have a new project in the works and it *may* utilize Laravel w/ GraphQL, and if it does I will (almost immediately) pick this package back up and continue to move forward with it's development and update the docs. 

However, I should point out that I am more than open to moving this project over to a new maintainer. I expect that this new project would carry on for several months at least but I don't know what the fate of Lighthouse would be after that. 

As far as it's current state, Laravel has had serval updates so I am uncertain how well it works with 5.5+. The mobile app that relies on it hasn't been updated since it's launch but it's been humming along just fine. If you're starting on a new project I might consider another package if one is available for the time being, and hopefully I can get back to maintaining this project shortly. 

Thanks!

**Comment by kikoseijo** [comment]
Thanks for the update, its much appreciated.
Happy coding!
