### ISSUE TITLE
Add a composable, extendable mechanism for nested mutations

### ISSUE THREAD

**Issue by spawnia** [nuwave/lighthouse#725]
**Is your feature request related to a problem? Please describe.**

As #692 and #691 have shown, the way that nested mutations are structured is not always the most elegant for particular use cases.

While it does have the basic building blocks to deal with any kind of relation,
the way the `MutationExecutor` is structured makes it so the implementation is set in stone.

**Describe the solution you'd like**

It would be nice if there was a simple way to extend the resolution process
and to offer an abstraction that makes it easier to compose nested mutations.

Similar to how the nested field resolution process works, we might be able to attach resolvers to specific arguments/input objects.

**Comment by JoeSchr** [comment]
Coming off the discussion from #692 and other times, I would just like to state that while I really respect the reasons for nested mutation mechanism to be very explicit, when I started to implemented graphql in our production, I dreamed of it being way more simple and less verbose.

To give an example: What I thought I could do was, fetch an json via a graphql query. e.g.
``` graphql
query allPersons() {
      person {
           ID
           name 
           tasks {
               ID
               name
          }
      }
```
then just use it via Vue/Vuex as a single state of truth, like a native js object: modifying it, adding, deleting, updating nested relationship simply by using it like a native array/object.

```javascript
     let state = { persons: [{
           ID: 1 
           name: "Person" 
           tasks: [{ID:1,name: "todo#1" },  {ID:2,name: "todo#3"},]
      }
]}
```

and then just post it back via e.g. 
``` updatePerson(state.person[0]) ```

without needing to transform all my changed nested relationships into a set of `update, connect, delete, sync` first. 
Because I figured the laravel backend already knows all the relationships between models anyway and just has to compare and sync accordingly (I had this kind of system build, of course specialized for my usecase and not generalisied, while working with REST before).


So if there would be a more abstracted API which makes implementing this kind of behavior easier while keeping it in sync with the rest of lighthouse development, I would be willing to put some time into building this.

**Comment by spawnia** [comment]
@JoeSchr i considered magic solutions like the reconciliation style mutation you are proposing. It could be very nice for simple use cases, but will only work for a constrained set of operations.

In no particular order, here are some thoughts and observations i already made while trying something similar.

- I think that you would have to limit it to updating nested children, but not parents. As far as i can tell, there is no real way to express the deletion of a BelongsTo relationship through this model.
- Performance might suffer, as the reconciliation process might require a bunch of round-trips to the database to compare before and after in order to determine what changes to make.
- The semantics for differentiating between a deletion and detaching are unclear.

If those issues can be addressed and the solution is general enough to be useful, i am open
to including it as an alternative to the current model.

If you want to discuss this particular idea further, let's do so in another issue or PR. The core of this issue is something different.

**Comment by lorado** [comment]
Are there any updates? 

I am new to lighthouse, but I was using some other GraphQL Library for Laravel. Unfortunately I have to change my lib, because it was a little underdevelped, and I got some issues in the functionality...

Anyway it was possible for me to define Input type in GraphQL with some custom input fields that were not a part of the model. I was able to define custom logic for this specific argument, and so I simply extended existing default behaviour.

In Details:

Im using HERE API, to get either polygon of selected area, or lat/lng of the selected city. My type looks like this:

```graphql
type RegionShapeInput {
  lat: Float
  lng: Float
  radius: Int
  shape: String
}

input RegionInput {
   shapeOrPoint: RegionShapeInput
}
```

This solution depends on business logic. If city was chosen, then we create a circle with 100km radius, if bigger area like state was chosen, then we store polygon of this area. So I have to decide what I have to store in DB depending on input.

Currently I think the easiest way to implement it with lighthouse is just to create mutation for storing regions. But it actually sucks, as I have to wait, till first mutation completes, when my parent model is not yet created. 

Or I have to write mutation and define whole logic by myself, but this seems to me bad chose, because I am not able to use beautiful implemented CRUD operations with nested mutations...

When this issue will be still open till October or November, I would probably ready to help to implement this feature...

**Comment by lorado** [comment]
An idea for extendable mechanism for nested mutations:

What if we introduce new directive for input argument, that calls some class method. So it is possible to define, how individual input argument has to be processed. But then this arguments should be ignored by typical `@create` or `@update` directives. Also there is the question, at what moment this method should be called. I think for overall solutions it should be possible to define, if this function should be called before or after regular resolver.

**Comment by spawnia** [comment]
@lorado you are on the right track with your idea.

Check out my work-in-progress and let me know what you think: #899
