### ISSUE TITLE
Versions 2.0.X not up to date with master

### ISSUE THREAD

**Issue by kikoseijo** [nuwave/lighthouse#92]
@chrissm79 , seems that if you just use the `composer require nuwave/lighthouse` the versions there are not properly up to date with master branch.

by default you will get today the 2.0.3 and this version as you can see comes with this fix we had several commits ago.

![screen shot 2018-04-27 at 02 05 43](https://user-images.githubusercontent.com/1528668/39337899-dce2558e-49bf-11e8-942b-5d43992ecd0b.png)

See picture? should be 'relay' instead of 'connection', and this is whats causing this strange behaviour on production builds.

A workaround will be to use the `composer require nuwave/lighthouse:dev-master` or master branch for now, I was wondering how you was doing the releases when no merges are carried, as you see in sourcetree graphical the branch never get merged.

I didn't notice till today because I was using `dev-master`.

Hope it helps- 

![screen shot 2018-04-27 at 02 13 00](https://user-images.githubusercontent.com/1528668/39338026-95cea048-49c0-11e8-84fc-914ec2bd268c.png)

**Comment by chrissm79** [comment]
Hey @kikoseijo, 

`v2.0.x` is for fixes for the `v2.0` release and it is the current release so that's what should be pulled down from composer. 

`master` is for beta (pre-releases). Once I have everything ready to go I'll cut `v2.1` and create a new `v2.1.x` branch that will just include fixes for version `2.1`. 

Hopefully that all made sense 😀
