### ISSUE TITLE
[Feat] Scout support

### ISSUE THREAD

**Issue by olivernybroe** [nuwave/lighthouse#93]
Thanks for supplying query to args directives, really helps alot!

So I am creating an Arg directive called `@search` for adding support for Laravel scout (fulltext search).

Is this something you would want in your package or should I make an extension for it?

**Comment by olivernybroe** [comment]
Yep, it's a single file. Just submitted a pull request for some changes which are needed for implementing this.

Hmm yeah we could add it in documentations, here is a gist with my directive.
https://gist.github.com/olivernybroe/2d2b164851b4fc7d4b62df8f37bfbb2a

**Comment by chrissm79** [comment]
@olivernybroe, love the idea and yes that would be awesome to submit a PR for it!! let me know if you have any questions or if there's anything I can help with!

**Comment by olivernybroe** [comment]
@chrissm79 I added a PR for some changes needed, however I didn't add the directive. 
The reason why I didn't add the directive is because Scout requires some Laravel features which we don't have in our package, and it would tie Lighthouse to Laravel and make it incompatible with Lumen.

I can add it without tests, or I can create a package so it can easily be added.
(not that great at composer, so it might be possible to add the tests with more knowledge there)

**Comment by 4levels** [comment]
Hi @olivernybroe,

I'll be looking into this since I have some experience with testing / porting Laravel libraries to Lumen.
I'm currently not very active with Lighthouse (I'm focussing on the app counterpart that actually consumes the Lighthouse features), but I expect to have time for this in the next couple of weeks..

Kind regards,

Erik

**Comment by 4levels** [comment]
Upon a first look, it pitty it that Scout seems to be configured with Algolia (a paid subscription service - only free for open source projects) only.  They claim it should be easy to integrate other search indexing services, just sad to see that ElasticSearch is not the preferred interface by default.

I do have some experience with ElasticSearch (and eg. Apache Solr) so I'll take it as a challenge to make Scout work with Lumen AND ElasticSearch instead of Algolia.

**Comment by olivernybroe** [comment]
For the test in lighthouse, we could just use fakes or maybe use TNT search? Just didn't felt like adding the directive without tests for it.

**Comment by chrissm79** [comment]
@olivernybroe You could add `laravel/scout` as a `dev` dependency (if there's a way to test it). It will just throw an exception if a user attempts to use the scout directive w/ out the composer package installed, but it means it won't pull it in when Lighthouse is installed in case the user doesn't plan on using scout or if it's incompatible w/ Lumen. Let me know if you have any questions or if there's anything I can help out with!

As for tests, [something like this](https://github.com/laravel/scout/blob/4.0/tests/MakeSearchableTest.php) might work.
