### ISSUE TITLE
[Feat] Support for apollo-tracing

### ISSUE THREAD

**Issue by TGNThump** [nuwave/lighthouse#98]
It would be amazing if we could add support for the Apollo tracing extension (https://github.com/apollographql/apollo-tracing).

**Comment by olivernybroe** [comment]
Hmm looks like they don't support webonyx/graphql-php, do we need the underlying package to support it and then we can support it afterwards?

**Comment by TGNThump** [comment]
Ah, yeah. webonyx/graphql-php has no extensions support implemented yet. :/
There is a PR for it (https://github.com/webonyx/graphql-php/pull/193), but apparently there is debate about which direction to take.

**Comment by chrissm79** [comment]
@TGNThump @olivernybroe This is something I've wanted to implement since I started development of v2.0. I haven't looked into it yet (Subscriptions is currently my top new feature priority). There's a few areas which might require a PR to `graphql-php` such as knowing the duration and startOffset of parsing and validation for the schema. As for the resolvers, it wouldn't be too hard to wrap each field resolver and send it's stats to a central `TraceExtension` repository to include in the response. I'll mark it as a 2.x feature for now and I'll keep this issue updated as I dig into it. PRs are more than welcome too 😄

**Comment by spawnia** [comment]
@chrissm79 does #199 resolve this? If so, this will be in v2.2!

**Comment by chrissm79** [comment]
Indeed it does!! I've only tested it in GraphQL Playground but @TGNThump if you're still having issues let me know and we'll reopen and investigate!

**Comment by eaverdeja** [comment]
@chrissm79 Tracing is not working for me. I'm using 

- PHP 7.1.3
- laravel-graphql-playground 0.3.3
- lighthouse 2.6.4
- laravel 5.7.21

Here's what shows up for me when clicking on the tracing option
![image](https://user-images.githubusercontent.com/4304022/53211912-aca7a780-3621-11e9-9daf-c5e40d782645.png)


Tracing would be really cool :+1:
