### ISSUE TITLE
Return value of Nuwave\Lighthouse\Execution\DataLoader\BatchLoader::buildKey() must be of the type string, null returned

### ISSUE THREAD

**Issue by PJijin** [nuwave/lighthouse#988]
I am getting this error on call.

<img src="https://i.imgur.com/PiOIc8V.png" />

Return value of Nuwave\\Lighthouse\\Execution\\DataLoader\\BatchLoader::buildKey() must be of the type string, null returned

The data is in relation

```
type OCProduct {
   images: OCProductImage @belongsTo
} 


type OCProductImage {
    product_image_id: Int 
    image: String 
}


```

Model 

Products model
```
 public function images()
    {
        return $this->belongsTo('App\OcProductImage', 'product_id', 'product_id');
    }
```

**Comment by spawnia** [comment]
The keys in your relation model off, which might be causing Lighthouse to fail to retrieve the correct key for `OCProduct`.

**Comment by robsontenorio** [comment]
@PJijin can you share your solution? I am facing same issue.

**Comment by PJijin** [comment]
@robsontenorio In my case, when I specify the private key field in the model it worked.

**Comment by robsontenorio** [comment]
@PJijin Can you show a sample?

**Comment by PJijin** [comment]
@robsontenorio I have followed this example. https://github.com/nuwave/lighthouse-example

In my case, the OCProduct private key was not id. I have to define that in model 

```
protected $primaryKey = 'product_id'; 
```

**Comment by ryancwalsh** [comment]
I just got this error too, and it's been one of a string of errors that I've spent hours on today.

I think I finally figured it out. Earlier today, I had to restore my database from a backup, and I'm now remembering that my backup was a bit stale in the sense that it was from before I'd manually running some script to create a primary key for a table that had only had a composite primary key (because of https://github.com/nuwave/lighthouse/issues/1064#issuecomment-643440729). I think once I adjust that table (again) to have its own primary key, everything will work again.
